### ISSUE TITLE
UI - Client or Server-side-rendering

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/LumiBox#8]
AFAIK that sort of asynchronous behaviour does not depend on where the page is rendered. Can be done either way.

So how about we just put some CSS on the current version and then have a little design session before we start working on this app "for real" after we got the proposals out?

_Originally posted by @rtens in https://github.com/Lumieducation/LumiBox/pull/6#issuecomment-472615517_

**Comment by rtens** [comment]
It seems like this, #3 and #7 are all discussing the same thing, correct? If so let's close this issue since it's redundant.
